# DNS analysis using CHAOS records
Questions:
* How common/reliable are version.bind records for identifying running DNS software
* Which DNS software is often used by DNS anycast operators?
* Do we see different DNS software used? (e.g., PoPs running different software/versions)
Data description:
* Data collected using 245 Ark VPs that support DNS probing
* Targets: 3,363 IPv4 anycast addresses that reply to DNS; 3,240 IPv6 anycast addresses
* Data format (.csv.gz)
* "vp_name" - name of the Ark VP that performed the measurement (includes city and country codes)
* "dst" - probed target address
* "qname" - CHAOS record queried (id.server, hostname.bind, version.bind)
* "rtt_ms" - time difference between sending and receiving (ms)
* "record" - record contained in the DNS response

In [1]:
import pandas as pd

In [2]:
# load in chaos data

chaosv4 = pd.read_csv('2026-01-16_DNSv4.csv.gz')
chaosv6 = pd.read_csv('2026-01-16_DNSv6.csv.gz')

# print(chaosv4.head())

# we only consider version.bind
# chaosv6 = chaosv6[chaosv6['qname'] == 'version.bind']
# chaosv4 = chaosv4[chaosv4['qname'] == 'version.bind']

chaosv4.head()

   vp_name            dst      qname  rtt_ms                    record
0  lax6-us   98.158.111.2  id.server    1.04  la-blue.ns-node.iptp.net
1  lax9-us   98.158.111.2  id.server    2.00  la-blue.ns-node.iptp.net
2  lax5-us  161.232.17.29  id.server    1.35                      LAX3
3   ful-us  161.232.17.29  id.server    2.17                      LAX4
4   bur-us  161.232.17.29  id.server    1.76                      LAX3

In [ ]:
# TODO get infra:ns from openintel to see which tld it hosts

In [3]:
# exploratory analysis
print("---ipv4---")
print(f"data from {chaosv4['vp_name'].nunique()} VPs")
print(f"towards {chaosv4['dst'].nunique()} targets that have a record")

# print number of servers supporting each chaos record
for record in chaosv4['qname'].unique():
    f = chaosv4.loc[chaosv4['qname'] == record]
    print(f"{f['dst'].nunique():,} targets that support {record}")

---ipv4---
data from 242 VPs
towards 2169 targets that have a record
1,438 targets that support id.server
2,108 targets that support hostname.bind
1,555 targets that support version.bind
424 targets that support version.server
350 targets that support authors.bind
29 targets that support server.bind

In [4]:
# exploratory analysis
print("---ipv6---")
print(f"data from {chaosv6['vp_name'].nunique()} VPs")
print(f"towards {chaosv6['dst'].nunique()} targets that have a record")

# print number of servers supporting each chaos record
for record in chaosv6['qname'].unique():
    f = chaosv6.loc[chaosv6['qname'] == record]
    print(f"{f['dst'].nunique():,} targets that support {record}")

---ipv6---
data from 73 VPs
towards 2018 targets that have a record
538 targets that support authors.bind
1,824 targets that support hostname.bind
1,133 targets that support id.server
1,584 targets that support version.bind
318 targets that support version.server
23 targets that support server.bind

In [5]:
# which dns software versions are there?

# common record values
chaosv4['record'].value_counts().reset_index()

                                         record  count
0                                             -  71041
1                                       9.11.22  54594
2      087a32084726a0bc478d318e0588d12ebe87fc56  41437
3                                   CIRA Server  28656
4                           UltraDNS Nameserver  15826
...                                         ...    ...
25815                                    960m95      1
25816                                  1232m111      1
25817                                    680m21      1
25818                                    786m94      1
25819                                    73m298      1

[25820 rows x 2 columns]

In [6]:
chaosv4[chaosv4['record'] == '9.11.22'].head() # -> bind version used in standard linux

        vp_name           dst         qname  rtt_ms   record
838151  sjc4-us  199.253.61.1  version.bind    1.60  9.11.22
838154  sjc6-us  199.253.61.1  version.bind    0.82  9.11.22
838192   mce-us  199.253.61.1  version.bind   10.61  9.11.22
838227  cld4-us  199.253.61.1  version.bind   19.48  9.11.22
838247   sdm-us    65.22.93.1  version.bind    6.72  9.11.22

In [7]:
chaosv4[chaosv4['record'] == '087a32084726a0bc478d318e0588d12ebe87fc56'].head() #

,vp_name,dst,qname,rtt_ms,record
838232,sdm-us,157.53.235.65,version.bind,36.03,087a32084726a0bc478d318e0588d12ebe87fc56
838246,sdm-us,45.54.97.129,version.bind,14.79,087a32084726a0bc478d318e0588d12ebe87fc56
838282,lax6-us,157.53.235.65,version.bind,33.41,087a32084726a0bc478d318e0588d12ebe87fc56
838284,lax4-us,157.53.235.65,version.bind,34.06,087a32084726a0bc478d318e0588d12ebe87fc56
838307,tij-mx,157.53.235.65,version.bind,33.91,087a32084726a0bc478d318e0588d12ebe87fc56

In [26]:
# init software

chaosv4['software'] = 'unknown'

## powerdns

In [27]:
# different types of powerdns values
chaosv4.loc[
    chaosv4['record'].str.lower().str.contains('powerdns', na=False),
    'software'
] = 'powerdns'

chaosv4[chaosv4['software'] == 'powerdns']['record'].unique()

array(['powerdns-2', 'powerdns-0', 'powerdns-1',
       'slave-gslb-powerdns-g7f2c', 'slave-gslb-powerdns-tz7cz',
       'slave-gslb-powerdns-gk7r9', 'slave-gslb-powerdns-qmmhp',
       'slave-gslb-powerdns-sjqxz', 'slave-gslb-powerdns-v78t2',
       'slave-gslb-powerdns-np4ct', 'slave-gslb-powerdns-qvf4k',
       'slave-gslb-powerdns-qdqbd', 'slave-gslb-powerdns-f5thw',
       'slave-gslb-powerdns-6dfhl', 'slave-gslb-powerdns-55k9v',
       'slave-gslb-powerdns-wwgq7', 'slave-gslb-powerdns-9rnf6',
       'slave-gslb-powerdns-2hvr7', 'slave-gslb-powerdns-mp7cp',
       'slave-gslb-powerdns-nvf8q', 'slave-gslb-powerdns-ntfzq',
       'slave-gslb-powerdns-xxckp', 'slave-gslb-powerdns-dmx5d',
       'slave-gslb-powerdns-z7gkh', 'slave-gslb-powerdns-pvj59',
       'slave-gslb-powerdns-9p54f', 'slave-gslb-powerdns-pj9lm',
       'slave-gslb-powerdns-7wt69', 'slave-gslb-powerdns-5vtwr',
       'slave-gslb-powerdns-bct8z', 'slave-gslb-powerdns-zzt9r',
       'slave-gslb-powerdns-4wjpc', 'slave-gslb-powerdns-2c6wr',
       'slave-gslb-powerdns-gtzcn', 'slave-gslb-powerdns-dx9b6',
       'slave-gslb-powerdns-rz7c9', 'slave-gslb-powerdns-tkbxq',
       'slave-gslb-powerdns-n745g', 'slave-gslb-powerdns-xmsfm',
       'slave-gslb-powerdns-m2pzb', 'slave-gslb-powerdns-9dw7x',
       'slave-gslb-powerdns-hhrp2', 'slave-gslb-powerdns-ghdlx',
       'slave-gslb-powerdns-rcxzh', 'slave-gslb-powerdns-k968k',
       'slave-gslb-powerdns-d4wfq', 'slave-gslb-powerdns-29p59',
       'slave-gslb-powerdns-x4gwz', 'slave-gslb-powerdns-wd2vj',
       'slave-gslb-powerdns-knxr4', 'slave-gslb-powerdns-dskxr',
       'slave-gslb-powerdns-fx88f', 'slave-gslb-powerdns-6kfn5',
       'slave-gslb-powerdns-2rbpm', 'slave-gslb-powerdns-jw6c6',
       'slave-gslb-powerdns-tltk2', 'slave-gslb-powerdns-bw6k7',
       'slave-gslb-powerdns-2ln8x', 'slave-gslb-powerdns-tzsqw',
       'slave-gslb-powerdns-gzrbf', 'slave-gslb-powerdns-hnxhp',
       'slave-gslb-powerdns-pz27h', 'slave-gslb-powerdns-w82nb',
       'slave-gslb-powerdns-krvhx', 'slave-gslb-powerdns-f6jvr',
       'slave-gslb-powerdns-lhmhs', 'slave-gslb-powerdns-fsqz2',
       'slave-gslb-powerdns-tldkq', 'slave-gslb-powerdns-d9xw9',
       'slave-gslb-powerdns-pwxpv', 'slave-gslb-powerdns-4rhsl',
       'slave-gslb-powerdns-m44kt', 'slave-gslb-powerdns-bh7pj',
       'slave-gslb-powerdns-vn7hv', 'slave-gslb-powerdns-f9sdr',
       'slave-gslb-powerdns-sbbn8', 'slave-gslb-powerdns-lspld',
       'slave-gslb-powerdns-5k5mv', 'slave-gslb-powerdns-kllwg',
       'slave-gslb-powerdns-tspwv', 'slave-gslb-powerdns-hgdgm',
       'slave-gslb-powerdns-jb8qv', 'slave-gslb-powerdns-gmqzl',
       'slave-gslb-powerdns-cqq5c', 'slave-gslb-powerdns-rdb9n',
       'slave-gslb-powerdns-s7kqq', 'slave-gslb-powerdns-48t82',
       'slave-gslb-powerdns-6z25f', 'slave-gslb-powerdns-w22mw',
       'slave-gslb-powerdns-x874p', 'slave-gslb-powerdns-6xfrj',
       'slave-gslb-powerdns-vskpg', 'slave-gslb-powerdns-p7vbl',
       'slave-gslb-powerdns-97ggz', 'slave-gslb-powerdns-c92nh',
       'slave-gslb-powerdns-rlgzv', 'slave-gslb-powerdns-kx78r',
       'slave-gslb-powerdns-jmxfc', 'slave-gslb-powerdns-5dvvx',
       'slave-gslb-powerdns-hddgj', 'slave-gslb-powerdns-97mqs',
       'slave-gslb-powerdns-cbd8x', 'slave-gslb-powerdns-zkddz',
       'slave-gslb-powerdns-dxd97', 'slave-gslb-powerdns-xhcfn',
       'slave-gslb-powerdns-l4pzn', 'slave-gslb-powerdns-7vf5l',
       'slave-gslb-powerdns-9mkr7', 'slave-gslb-powerdns-tpkbp',
       'slave-gslb-powerdns-clssq', 'slave-gslb-powerdns-2m42s',
       'slave-gslb-powerdns-z9dhm', 'slave-gslb-powerdns-9h8w5',
       'slave-gslb-powerdns-7kb6p', 'slave-gslb-powerdns-48pz9',
       'slave-gslb-powerdns-mmfpr', 'slave-gslb-powerdns-sszbn',
       'slave-gslb-powerdns-vwn55', 'slave-gslb-powerdns-dwkjj',
       'PowerDNS Recursor 4.9.3 (built Feb 13 2024 13:46:08 by buildozer@localhost)',
       'Served by PowerDNS - https://www.powerdns.com/',
       'PowerDNS Authoritative Server 4.5.3',
       'PowerDNS Authoritative Server 4.9.5 (built Aug 26 2025 11:35:14 by root@bh-centos-8.dev.cpanel.net)',
       'PowerDNS Authoritative Server 4.9.7 (built Jul  7 2025 07:51:20 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.1 (built Jul 19 2024 14:43:27 by root@bh-centos-7.dev.cpanel.net)',
       'PowerDNS Authoritative Server 4.2.1-2.69.1 (built Dec 19 2024 07:23:56 by jenkins@hk1-gslb-jenkins-154)',
       'PowerDNS Authoritative Server 4.9.5 (built May 12 2025 13:41:30 by root@bh-centos-8.dev.cpanel.net)',
       'PowerDNS Authoritative Server 4.9.12 (built Dec 11 2025 09:08:16 by root@localhost)',
       'PowerDNS Authoritative Server 4.7.4 (built Mar 10 2025 18:43:19 by portage@localhost)',
       'PowerDNS Authoritative Server 4.1.1',
       'PowerDNS Authoritative Server 4.8.3',
       'PowerDNS Authoritative Server 4.9.2 (built Dec 19 2024 15:24:48 by root@bh-centos-7.dev.cpanel.net)',
       'PowerDNS-Recursor',
       'PowerDNS Authoritative Server 4.2.3 (built Sep 22 2020 16:57:47 by root@faf12a948d7d)',
       'PowerDNS Authoritative Server unknown (built Jun 25 2025 04:39:00 by root@lax-dns-10344-108-181-16-165)',
       'PowerDNS Authoritative Server unknown (built Sep 25 2020 07:45:09 by root@dns1.psychz.net)',
       'PowerDNS Authoritative Server unknown (built Sep 25 2020 15:53:54 by root@dns4)',
       'PowerDNS Authoritative Server 4.4.3 (built Mar 21 2022 09:01:54 by root@d87702b22cbd)',
       'PowerDNS Authoritative Server unknown (built Jun 11 2020 00:19:47 by root@chi2.cdn)',
       'redirect.pizza Authoritative DNS lax0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS dfw0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS sjc0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'PowerDNS Authoritative Server 4.9.5 (built May  7 2025 09:37:57 by root@localhost)',
       'redirect.pizza Authoritative DNS ord0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'PowerDNS Authoritative Server 0.0.0.0.master.gaf198a4d1b (built Sep 19 2025 06:31:53 by root@ams-12752-dns-108-181-123-3)',
       'redirect.pizza Authoritative DNS sea0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'PowerDNS Authoritative Server unknown (built Sep 12 2020 09:28:21 by root@dns-jnb-11830)',
       'redirect.pizza Authoritative DNS ewr0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'PowerDNS Authoritative Server unknown (built Jun 30 2020 00:46:29 by root@dns-sao-15031)',
       'PowerDNS Authoritative Server unknown (built Jun 30 2020 04:17:59 by root@dns-bcn-14252)',
       'redirect.pizza Authoritative DNS icn0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'PowerDNS Authoritative Server unknown (built Jun 30 2020 12:36:05 by root@dns-sk-16458)',
       'PowerDNS Authoritative Server unknown (built Jun 29 2020 23:46:05 by root@dns-mum-13451)',
       'redirect.pizza Authoritative DNS lhr0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS fra0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS yto0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS syd0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS nrt0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS mad0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS hnl0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS mex0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS sao0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS sgp0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS sto0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS ams0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS bom0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS ams1.prod.edge.redirect.pizza (powered by PowerDNS)',
       'redirect.pizza Authoritative DNS jnb0.prod.edge.redirect.pizza (powered by PowerDNS)',
       'PowerDNS Recursor 5.0.7 (built Jul  2 2024 07:18:08 by root@localhost)',
       'PowerDNS Authoritative Server 4.5.5 (built Dec  8 2022 18:24:18 by root@a309361b6303)',
       'PowerDNS Authoritative Server 4.3.1 (built Nov 17 2020 02:50:36 by root@ns-lon.retn.net)',
       'PowerDNS Recursor 5.2.2 (built Apr  8 2025 10:42:32 by root@localhost)',
       'PowerDNS Recursor 5.3.3 (built Dec  8 2025 10:57:22 by root@localhost)',
       'PowerDNS Recursor 5.1.0 (built Jul  9 2024 10:51:40 by root@localhost)',
       'PowerDNS Authoritative Server 4.0.4 (built Nov 23 2017 18:27:22 by root@ns-hkg.retn.net)',
       'PowerDNS Recursor 5.2.6 (built Oct 22 2025 10:09:31 by root@localhost)',
       'PowerDNS Recursor 5.0.7 (built Jul  2 2024 07:18:56 by root@localhost)',
       'PowerDNS Authoritative Server 4.6.4 (built Dec  8 2022 18:40:08 by root@fffc985daece)',
       'PowerDNS Recursor 5.2.7 (built Dec  8 2025 10:43:49 by root@localhost)',
       'PowerDNS Recursor 5.3.3 (built Dec  8 2025 10:54:02 by root@localhost)',
       'PowerDNS Recursor 5.1.4 (built Apr  8 2025 10:11:44 by root@localhost)',
       'PowerDNS Recursor 5.1.3 (built Nov  4 2024 11:22:02 by root@localhost)',
       'PowerDNS Authoritative Server 4.3.0 (built Sep  2 2020 13:19:54 by root@pdns-template)',
       'PowerDNS Recursor 5.1.9 (built Dec  8 2025 10:41:02 by root@localhost)',
       'PowerDNS Recursor 5.0.12 (built Jul 17 2025 10:33:37 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.12 (built Dec 11 2025 09:02:11 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.5 (built May 12 2025 00:00:00 by root@bh-centos-9.dev.cpanel.net)',
       'PowerDNS Authoritative Server 4.9.5 (built May  7 2025 09:30:59 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.11.0.HEAD.ga050f798b (built Nov 29 2025 22:23:30 by root@localhost)',
       'PowerDNS Authoritative Server 4.8.5 (built Feb  7 2025 09:21:23 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.9 (built Sep 23 2025 14:07:02 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.5 (built Aug 26 2025 00:00:00 by root@bh-centos-9.dev.cpanel.net)',
       'PowerDNS Authoritative Server 4.9.5 (built May  7 2025 09:37:48 by root@localhost)',
       'PowerDNS Authoritative Server 5.0.0 (built Aug 22 2025 07:21:02 by root@localhost)',
       'PowerDNS Authoritative Server 4.1.13 (built Aug  8 2019 07:52:12 by root@0375968a661f)',
       'PowerDNS Authoritative Server 4.1.6',
       'PowerDNS Authoritative Server 4.8.3 (built Nov 15 2023 11:38:56 by buildozer@localhost)',
       'PowerDNS Authoritative Server 4.2.1',
       'PowerDNS Authoritative Server 4.9.3 (built Dec 16 2024 08:52:59 by root@localhost)',
       'PowerDNS Authoritative Server 4.0.6',
       'PowerDNS Authoritative Server 4.1.8',
       'PowerDNS Authoritative Server 4.9.4 (built Feb  6 2025 15:18:23 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.4 (built Feb  6 2025 15:18:31 by root@localhost)',
       'PowerDNS Authoritative Server 4.1.14',
       'PowerDNS Authoritative Server 4.1.11',
       'PowerDNS Authoritative Server 4.5.4 (built Mar 31 2022 10:17:12 by buildozer@build-3-15-x86_64)',
       'PowerDNS Recursor 5.3.3 (built Dec  8 2025 10:57:35 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.2 (built Sep 30 2024 10:41:11 by root@localhost)',
       'PowerDNS Authoritative Server 4.5.1 (built Jul 22 2021 11:42:23 by root@82ff20dd7c90)',
       'PowerDNS Authoritative Server 4.9.9 (built Sep 23 2025 15:11:29 by root@localhost)',
       'PowerDNS Authoritative Server 5.0.2 (built Dec 11 2025 09:01:16 by root@localhost)',
       'PowerDNS Authoritative Server 4.0.9 (built Jul 30 2019 23:02:16 by root@eb17f64a8441)',
       'PowerDNS Authoritative Server 4.9.2 (built Feb 24 2025 00:00:00 by root@bh-centos-9.dev.cpanel.net)',
       'PowerDNS Authoritative Server 5.0.0',
       'PowerDNS Authoritative Server 4.9.9 (built Sep 23 2025 14:07:44 by root@localhost)',
       'PowerDNS Authoritative Server 4.3.1 (built Sep 22 2020 11:06:50 by root@0011ecbed8d3)',
       'PowerDNS Authoritative Server 4.9.5 (built May  7 2025 09:30:51 by root@localhost)',
       'PowerDNS Authoritative Server 4.4.3 (built Mar 21 2022 08:53:11 by root@ac43cdd096d3)',
       'PowerDNS Authoritative Server 4.0.7 (built Mar 18 2019 10:51:56 by root@7354daadbdeb)',
       'PowerDNS Authoritative Server 4.5.2 (built Feb 23 2022 10:48:15 by portage@localhost)',
       'PowerDNS Authoritative Server 4.7.5 (built Feb  7 2025 09:28:49 by root@localhost)',
       'PowerDNS Authoritative Server 4.6.3 (built Oct  6 2022 07:18:57 by portage@localhost)',
       'PowerDNS Authoritative Server 5.0.0-alpha0.1455.master.gb69f97caf (built Aug 19 2024 04:17:47 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.2 (built Dec 26 2024 07:39:51 by portage@AH1798)',
       'PowerDNS Authoritative Server 4.9.3 (built Oct 30 2025 17:25:35 by portage@DS9732)',
       'PowerDNS Authoritative Server 4.6.1 (built May 23 2022 16:12:55 by portage@DS9731)',
       'PowerDNS Authoritative Server 4.9.2 (built Dec 16 2024 14:22:39 by portage@AH1797)',
       'PowerDNS Authoritative Server 4.9.1 (built Oct 17 2024 14:49:48 by portage@DS8321)',
       'PowerDNS Authoritative Server 4.9.0-beta2.9.master.g22c29777a (built Feb 16 2024 15:41:23 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.1 (built Oct 17 2024 14:48:40 by portage@DS8320)',
       'PowerDNS Authoritative Server 4.9.5 (built May  8 2025 21:16:08 by buildozer@localhost)',
       'PowerDNS Authoritative Server 4.8.3 (built Nov 15 2023 11:38:56 by buildozer@build-3-19-aarch64.local)',
       'PowerDNS Authoritative Server 4.8.4 (built Dec 19 2023 08:24:58 by root@localhost)',
       'PowerDNS Authoritative Server 4.7.3 (built Dec  8 2022 19:07:29 by root@f89f3d44de25)',
       'PowerDNS Authoritative Server 4.6.0-alpha1.508.master.g853e27067 (built Dec  6 2021 17:01:17 by root@04eec520955d)',
       'PowerDNS Authoritative Server 0.0.28191.0.HEAD.g6266fb1217 (built Oct 31 2025 17:47:21 by netskrt@df31ee8c457a)',
       'PowerDNS Authoritative Server 0.0.28191.0.HEAD.g6266fb1217 (built Jan  8 2026 21:11:28 by netskrt@290fa396b992)',
       'PowerDNS Authoritative Server 5.0.0 (built Aug 22 2025 07:29:17 by root@localhost)',
       'PowerDNS Authoritative Server 5.0.1 (built Oct 30 2025 10:37:20 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.4',
       'PowerDNS Authoritative Server 4.6.4 (built Dec  8 2022 18:54:21 by root@8f5c45201b56)',
       'PowerDNS Authoritative Server 4.5.5 (built Dec  8 2022 18:11:18 by root@413bd54b27a2)',
       'PowerDNS Authoritative Server 4.8.4 (built Dec 19 2023 08:25:01 by root@localhost)',
       'PowerDNS Authoritative Server 4.8.4 (built Feb  6 2024 00:00:00 by mockbuild@localhost)',
       'PowerDNS Authoritative Server 4.9.7 (built Jul  7 2025 07:43:42 by root@localhost)',
       'PowerDNS Authoritative Server 4.9.7',
       'Egontek PowerDNS server (ns1-america-usa-ny.egontek.net)',
       'Egontek PowerDNS server (ns1-europe-nl.egontek.net)',
       'PowerDNS Authoritative Server 4.4.1'], dtype=object)

In [30]:
# number of dns servers running powerdns
chaosv4[chaosv4['software'] == 'powerdns']['dst'].nunique()

199

## knot

In [32]:
chaosv4.loc[
    chaosv4['record'].str.lower().str.contains('knot', na=False),
    'software'
] = 'knot'

chaosv4[chaosv4['software'] == 'knot']['record'].unique()

array(['reg-ffm1_customer15_knot', 'reg-ffm1_customer14_knot',
       'reg-rey1_customer14_knot', 'reg-prs1_shared1_knot',
       'reg-rey1_shared1_knot', 'ns-1.es.us4.knot', 'ns-2.es.us3.knot',
       'ns-2.es.us4.knot', 'ns-1.es.at1.knot', 'ns-2.es.kr1.knot',
       'ns-1.es.kr1.knot', 'ns-2.cira.us3.knot', 'ns-2.cira.kr1.knot',
       'ns-2.cira.de2.knot', 'ns-1.cira.at1.knot', 'ns-1.cira.de2.knot',
       'reg-ffm1_customer5_knot', 'ns-2.de.kr1.knot',
       'Knot - NIC Chile - cph', 'Knot - NIC Chile - elbosque',
       'ns-1.de.kr1.knot', 'ns-2.lu.us4.knot', 'ns-1.lu.us4.knot',
       'ns-2.lu.kr1.knot', 'ns-1.lu.kr1.knot', 'ns-1.lu.at1.knot',
       'ns-2.fi.us4.knot', 'ns-1.fi.us4.knot', 'ns-1.fi.at1.knot',
       'ns-1.fi.kr1.knot', 'ns-2.fi.kr1.knot',
       'Knot - NIC Chile - amsterdam', 'Knot - NIC Chile - saopaulo',
       'ns-1.eu.us4.knot', 'ns-2.eu.us4.knot', 'ns-1.eu.at1.knot',
       'ns-1.eu.kr1.knot', 'ns-2.eu.kr1.knot',
       'Knot - NIC Chile - londres', 'Knot - NIC Chile - huechuraba',
       'ns-1.bg.us4.knot', 'ns-2.bg.us4.knot', 'ns-1.bg.kr1.knot',
       'ns-1.bg.at1.knot', 'ns-2.bg.kr1.knot', 'ns-1.de.de8.knot',
       'ns-1.de.nl1.knot', 'ns-2.de.nl1.knot', 'ns-1.cira.kr1.knot',
       'knot 3.x', 'Knot DNS 3.2.9', 'Knot DNS 3.3.4', 'Knot DNS 3.4.4',
       'Knot DNS 3.0.10', 'Knot DNS 3.2.13', 'ns-1.es.us3.knot',
       'ns-1.cira.us3.knot', 'Knot DNS 3.1.2.1757486957.363aa7306',
       'Knot DNS 3.4.7', 'Knot DNS 3.4.8', 'Knot DNS 3.4.3',
       'Knot DNS 3.5.2', 'Knot DNS',
       'Knot DNS 3.1.2.1767687783.36033922a', 'Knot DNS 3',
       'Knot DNS 2.9.9', 'Knot DNS 3.1.9', 'Knot DNS 3.3.10',
       'Knot DNS 3.5.1', 'ns-2.de.de8.knot'], dtype=object)

In [33]:
chaosv4[chaosv4['software'] == 'knot']['dst'].nunique()

48

## bind

In [90]:
chaosv4.loc[
    chaosv4['record'].str.lower().str.contains(r'bind|9\.11\.22|michael graff|brian wellington|mark andrews|bob halley|james brister|michael sawyer', case=False, na=False, regex=True),
    'software'
] = 'bind'
chaosv4[chaosv4['software'] == 'bind']['record'].unique()

array(['ns-2.es.nl1.bind', 'ns-1.es.de2.bind', 'ns-1.es.se1.bind',
       'ns-1.es.nl1.bind', 'ns-2.es.se1.bind', 'ns-2.es.de2.bind',
       'ns.es.hk2.bind', 'ns-1.es.de8.bind', 'ns-2.es.br1.bind',
       'ns.es.fr2.bind', 'ns.es.bg1.bind', 'ns.es.in1.bind',
       'ns.es.sg1.bind', 'ns.es.pl1.bind', 'ns-1.es.br1.bind',
       'ns-1.cira.us4.bind', 'ns-2.cira.us4.bind', 'ns-1.cira.de8.bind',
       'ns.cira.bg1.bind', 'ns.cira.pl1.bind', 'ns.cira.fr3.bind',
       'ns.cira.anx-jnb1.bind', 'ns.cira.anx-sydney1.bind',
       'ns.cira.hk2.bind', 'ns-2.cira.se1.bind', 'ns-1.cira.nl1.bind',
       'ns-2.cira.cn1.bind', 'ns-2.cira.nl1.bind', 'ns.cira.anx-uk2.bind',
       'ns.cira.sg1.bind', 'ns-2.cira.br1.bind', 'ns-1.cira.se1.bind',
       'ns.cira.in1.bind', 'ns.cira.fr2.bind', 'ns-1.cira.cn1.bind',
       'ns-1.cira.br1.bind', 'ns-1.de.us4.bind', 'ns.de.mx1.bind',
       'ns-2.de.us3.bind', 'ns-2.de.us4.bind', 'ns-1.de.de2.bind',
       'ns.de.sg1.bind', 'ns-2.de.de2.bind', 'ns.de.fr2.bind',
       'ns.de.ae1.bind', 'ns-2.de.cn1.bind', 'ns-1.de.cn1.bind',
       'ns.de.pl1.bind', 'ns.de.in1.bind', 'ns-2.lu.us3.bind',
       'ns-1.lu.de2.bind', 'ns-2.lu.de2.bind', 'ns-1.lu.se1.bind',
       'ns-2.lu.se1.bind', 'ns-2.lu.nl1.bind', 'ns.lu.sg1.bind',
       'ns.lu.hk2.bind', 'ns.lu.bg1.bind', 'ns-1.lu.br1.bind',
       'ns-1.lu.de8.bind', 'ns-1.lu.nl1.bind', 'ns-2.lu.br1.bind',
       'ns.lu.fr2.bind', 'ns.lu.pl1.bind', 'ns.lu.in1.bind',
       'ns-2.fi.us3.bind', 'ns-2.fi.de2.bind', 'ns-2.fi.se1.bind',
       'ns-1.fi.nl1.bind', 'ns-1.fi.de2.bind', 'ns.fi.bg1.bind',
       'ns-2.fi.br1.bind', 'ns.fi.hk2.bind', 'ns-1.fi.se1.bind',
       'ns-2.fi.nl1.bind', 'ns-1.fi.de8.bind', 'ns.fi.pl1.bind',
       'ns.fi.sg1.bind', 'ns-1.fi.br1.bind', 'ns.fi.fr2.bind',
       'ns.fi.in1.bind', 'ns-2.eu.us3.bind', 'ns-1.eu.de2.bind',
       'ns-2.eu.de2.bind', 'ns-1.eu.de8.bind', 'ns-2.eu.se1.bind',
       'ns.eu.bg1.bind', 'ns-1.eu.nl1.bind', 'ns-2.eu.nl1.bind',
       'ns.eu.pl1.bind', 'ns-1.eu.br1.bind', 'ns.eu.hk2.bind',
       'ns-1.eu.se1.bind', 'ns.eu.sg1.bind', 'ns-2.eu.br1.bind',
       'ns.eu.fr2.bind', 'ns.eu.in1.bind', 'ns-2.nic.uk1.bind',
       'ns-1.nic.fr1.bind', 'ns-1.nic.uk1.bind', 'ns-2.nic.fr1.bind',
       'ns-2.bg.us3.bind', 'ns-2.bg.se1.bind', 'ns-1.bg.nl1.bind',
       'ns-1.bg.se1.bind', 'ns-1.bg.de2.bind', 'ns-2.bg.de2.bind',
       'ns-1.bg.de8.bind', 'ns-2.bg.nl1.bind', 'ns.bg.hk2.bind',
       'ns-2.bg.br1.bind', 'ns-1.bg.br1.bind', 'ns.bg.sg1.bind',
       'ns.bg.in1.bind', 'ns-1.de.at1.bind', 'ns-1.de.se1.bind',
       'ns.de.fr3.bind', 'ns.de.hk2.bind', 'ns-2.de.se1.bind',
       'ns.de.us6.bind', 'ns.de.anx-sydney1.bind', 'ns.de.cl1.bind',
       'ns.de.anx-jnb1.bind', 'lax1-1-bind9', 'sea1-1-bind9',
       'hnl1-1-bind9', 'sjc1-1-bind9', 'atl1-1-bind9', 'ord1-1-bind9',
       'ewr1-2-bind9', 'yyz1-1-bind9', 'mia1-1-bind9', 'mex1-1-bind9',
       'dfw1-1-bind9', 'mad1-1-bind9', 'mel1-1-bind9', 'fra1-1-bind9',
       'syd1-1-bind9', 'icn1-1-bind9', 'nrt1-1-bind9', 'lhr1-1-bind9',
       'ams1-2-bind9', 'itm1-1-bind9', 'scl1-1-bind9', 'gru1-2-bind9',
       'man1-1-bind9', 'cdg1-1-bind9', 'sin1-1-bind9', 'waw1-1-bind9',
       'arn1-1-bind9', 'tlv1-1-bind9', 'del1-1-bind9', 'bom1-1-bind9',
       'blr1-1-bind9', 'jnb1-1-bind9', 'mqnvpubind02', 'usa-bind',
       'bind-usa-02', 'bind-recersive', 'bind-recursive-02',
       'NIC Chile - BIND 9 - monterreyb', 'NIC Chile - BIND 9 - lima',
       'NIC Chile - BIND 9 - praga2', 'NIC Chile - BIND 9 - blanco',
       'NIC Chile - BIND 9 - praga', 'NIC Chile - BIND 9 - merced',
       'NIC Chile - BIND 9 - beaucheff', 'NIC Chile - BIND 9 - agustinas',
       'ns.bg.fr2.bind', '9.11.22', 'BIND', 'BIND INFOMANIAK', 'bind 9.x',
       'ns-2.es.de8.bind', 'ns-2.cira.de8.bind', 'ns-1.de.us3.bind',
       'ns-1.lu.us3.bind', 'ns-1.fi.us3.bind', 'ns-2.fi.de8.bind',
       'ns-2.lu.de8.bind', 'My name is Bind. James Bind. Version 007',
       'ns-1.eu.us3.bind', 'ns-2.eu.de8.bind',
       'NIC Chile - BIND 9 - sec-miami',
       'NIC Chile - BIND 9 - sec-merced',
       'NIC Chile - BIND 9 - sec-blanco',
       'NIC Chile - BIND 9 - sec-huechuraba',
       'NIC Chile - BIND 9 - sec-vina', 'ns-1.bg.us3.bind',
       'ns.bg.bg1.bind', 'Brian Wellington', 'Mark Andrews',
       'James Brister', 'Bob Halley', 'Michael Sawyer', 'Michael Graff'],
      dtype=object)

In [85]:
chaosv4[chaosv4['software'] == 'bind']['dst'].nunique()

356

## redhat

In [36]:
chaosv4.loc[
    chaosv4['record'].str.lower().str.contains('redhat', na=False),
    'software'
] = 'redhat'

chaosv4[chaosv4['software'] == 'redhat']['record'].unique()

array(['9.11.26-RedHat-9.11.26-6.el8',
       '9.3.6-P1-RedHat-9.3.6-4.P1.el5_5.3',
       '9.9.4-RedHat-9.9.4-73.el7_6',
       '9.11.4-P2-RedHat-9.11.4-16.P2.el7_8.6',
       '9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.13',
       '9.11.4-P2-RedHat-9.11.4-9.P2.el7',
       '9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.4',
       '9.9.4-RedHat-9.9.4-61.el7', '9.11.13-RedHat-9.11.13-6.el8_2.1',
       '9.11.4-P2-RedHat-9.11.4-26.P2.amzn2.13',
       '9.11.4-P2-RedHat-9.11.4-26.P2.amzn2.13.11',
       '9.11.4-P2-RedHat-9.11.4-9.P2.amzn2.0.2',
       '9.11.4-P2-RedHat-9.11.4-9.P2.amzn2.0.4',
       '9.11.4-P2-RedHat-9.11.4-26.P2.amzn2.4',
       '9.11.4-P2-RedHat-9.11.4-26.P2.amzn2.5.2',
       '9.11.36-RedHat-9.11.36-16.el8_10.6',
       '9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.15',
       '9.8.2rc1-RedHat-9.8.2-0.47.rc1.el6',
       '9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.16',
       '9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.10'], dtype=object)

In [37]:
chaosv4[chaosv4['software'] == 'redhat']['dst'].nunique()

23

## unbound

In [41]:
chaosv4.loc[
    chaosv4['record'].str.lower().str.contains('unbound', na=False),
    'software'
] = 'unbound'

chaosv4[chaosv4['software'] == 'unbound']['record'].unique()

array([], dtype=object)

In [42]:
chaosv4[chaosv4['software'] == 'unbound']['dst'].nunique()

0

## core

In [43]:
chaosv4.loc[
    chaosv4['record'].str.lower().str.contains('core', na=False),
    'software'
] = 'core'

chaosv4[chaosv4['software'] == 'core']['record'].unique()

array(['drc-v-wgdns-3.be.core.pw', 'drc-v-wgdns-4.be.core.pw',
       'anx-v-wgdns-3.be.core.pw', 'anx-v-wgdns-4.be.core.pw',
       'am3-v-wgdns-3.be.core.pw', 'am3-v-wgdns-4.be.core.pw',
       'sg2-v-wgdns-3.be.core.pw', 'sg2-v-wgdns-4.be.core.pw',
       'core-ns-edge-uslax-0', 'core-ns-edge-uslax-1',
       'core-ns-edge-usnyc-1', 'core-ns-edge-usnyc-0',
       'core-ns-edge-sgsin-0', 'core-ns-edge-esmad-0',
       'core-ns-edge-defra-0', 'core-ns-edge-frpar-0',
       'core-ns-edge-nlams-0', 'core-ns-edge-uklon-0',
       'core-ns-edge-sgsin-1', 'core-ns-edge-sesto-0',
       'core-ns-edge-itmil-0', 'core-ns-edge-lubet-1',
       'core-ns-edge-lubet-0', 'core-ns-edge-lukyl-0',
       'core-ns-edge-hubud-0', 'core01a.adectra.com',
       'dnsaut-co-02-parild2.core.wifirst.net',
       'dnsaut-co-02-loneq8.core.wifirst.net',
       'dnsaut-co-02-lonthe.core.wifirst.net',
       'dnsaut-co-02-pareq2.core.wifirst.net', 'CoreDNS-3.0.0',
       'CoreDNS-3.0.1', 'CoreDNS-2.9.13'], dtype=object)

In [44]:
chaosv4[chaosv4['software'] == 'core']['dst'].nunique()

9

## dnsmasq

In [73]:
chaosv4.loc[
    chaosv4['record']
        .str.lower()
        .str.contains(r'dnsmasq|simon kelley', na=False),
    'software'
] = 'dnsmasq'

chaosv4[chaosv4['software'] == 'dnsmasq']['record'].unique()

array(['dnsmasq-2.83', 'dnsmasq-2.78', 'Simon Kelley'], dtype=object)

In [74]:
chaosv4[chaosv4['software'] == 'dnsmasq']['dst'].nunique()

1555

# ultradns (propietary)

In [94]:
chaosv4.loc[
    chaosv4['record']
        .str.lower()
        .str.contains(r'ultradns|ultra', na=False),
    'software'
] = 'ultradns'

chaosv4[chaosv4['software'] == 'ultradns']['record'].unique()

array(['rcrsv1.uslax1.ultradns', 'rcrsv2.uslax1.ultradns',
       'rcrsv4.uslax1.ultradns', 'rcrsv1.ussea1.ultradns',
       'rcrsv3.uslax1.ultradns', 'rcrsv2.usdal1.ultradns',
       'rcrsv4.usdal1.ultradns', 'rcrsv2.cator1.ultradns',
       'rcrsv4.jptyo1.ultradns', 'rcrsv1.usdal1.ultradns',
       'rcrsv3.uswas1.ultradns', 'rcrsv2.uswas1.ultradns',
       'rcrsv1.uswas1.ultradns', 'rcrsv4.uswas1.ultradns',
       'rcrsv3.cator1.ultradns', 'rcrsv2.jptyo1.ultradns',
       'rcrsv4.cator1.ultradns', 'rcrsv4.usnyc1.ultradns',
       'rcrsv1.usmia1.ultradns', 'rcrsv1.usatl1.ultradns',
       'rcrsv1.uschi1.ultradns', 'rcrsv4.gblon1.ultradns',
       'rcrsv2.sesto1.ultradns', 'rcrsv3.sesto1.ultradns',
       'rcrsv1.sesto1.ultradns', 'rcrsv1.defra1.ultradns',
       'rcrsv3.gblon1.ultradns', 'rcrsv3.defra1.ultradns',
       'rcrsv3.usdal1.ultradns', 'rcrsv2.uschi1.ultradns',
       'rcrsv2.defra1.ultradns', 'rcrsv4.ausyd1.ultradns',
       'rcrsv2.gblon1.ultradns', 'rcrsv2.brsao1.ultradns',
       'rcrsv4.defra1.ultradns', 'rcrsv1.ausyd1.ultradns',
       'rcrsv3.nlams1.ultradns', 'rcrsv1.jptyo1.ultradns',
       'rcrsv1.usnyc1.ultradns', 'rcrsv1.gblon1.ultradns',
       'rcrsv4.sgsin1.ultradns', 'rcrsv2.usatl1.ultradns',
       'rcrsv2.usmia1.ultradns', 'rcrsv1.cator1.ultradns',
       'rcrsv3.ausyd1.ultradns', 'rcrsv3.sgsin1.ultradns',
       'rcrsv1.indel1.ultradns', 'rcrsv2.inbom1.ultradns',
       'rcrsv2.ausyd1.ultradns', 'rcrsv1.sgsin1.ultradns',
       'rcrsv2.hkhkg1.ultradns', 'rcrsv2.indel1.ultradns',
       'rcrsv4.sesto1.ultradns', 'rcrsv1.brsao1.ultradns',
       'rcrsv2.sgsin1.ultradns', 'rcrsv3.brsao1.ultradns',
       'rcrsv2.zajnb1.ultradns', 'rcrsv1.zajnb1.ultradns',
       'rcrsv1.nlams1.ultradns', 'ddr-rcsv1.uslax1.prod.ultradns.net',
       'ddr-rcsv2.uslax1.prod.ultradns.net',
       'ddr-rcsv2.uswas1.prod.ultradns.net',
       'ddr-rcsv1.usdal1.prod.ultradns.net',
       'ddr-rcsv2.uschi1.prod.ultradns.net',
       'ddr-rcsv1.ussea1.prod.ultradns.net',
       'ddr-rcsv2.usdal1.prod.ultradns.net',
       'ddr-rcsv1.uswas1.prod.ultradns.net',
       'ddr-rcsv2.usatl1.prod.ultradns.net',
       'ddr-rcsv1.usatl1.prod.ultradns.net',
       'ddr-rcsv1.cator1.prod.ultradns.net',
       'ddr-rcsv2.usmia1.prod.ultradns.net',
       'ddr-rcsv2.jptyo1.prod.ultradns.net',
       'ddr-rcsv1.gblon1.prod.ultradns.net',
       'ddr-rcsv2.nlams1.prod.ultradns.net',
       'ddr-rcsv1.nlams1.prod.ultradns.net',
       'ddr-rcsv2.frpar1.prod.ultradns.net',
       'ddr-rcsv2.cator1.prod.ultradns.net',
       'ddr-rcsv1.jptyo1.prod.ultradns.net',
       'ddr-rcsv1.usmia1.prod.ultradns.net',
       'ddr-rcsv1.defra1.prod.ultradns.net',
       'ddr-rcsv2.gblon1.prod.ultradns.net',
       'ddr-rcsv2.brsao1.prod.ultradns.net',
       'ddr-rcsv2.usnyc1.prod.ultradns.net',
       'ddr-rcsv2.ausyd1.prod.ultradns.net',
       'ddr-rcsv1.ausyd1.prod.ultradns.net',
       'ddr-rcsv2.sgsin1.prod.ultradns.net',
       'ddr-rcsv1.frpar1.prod.ultradns.net',
       'ddr-rcsv2.defra1.prod.ultradns.net',
       'ddr-rcsv1.brsao1.prod.ultradns.net',
       'ddr-rcsv1.sesto1.prod.ultradns.net',
       'ddr-rcsv1.sgsin1.prod.ultradns.net',
       'ddr-rcsv2.sesto1.prod.ultradns.net',
       'ddr-rcsv1.inbom1.prod.ultradns.net',
       'ddr-rcsv2.indel1.prod.ultradns.net',
       'ddr-rcsv2.zajnb1.prod.ultradns.net',
       'ddr-rcsv1.indel1.prod.ultradns.net',
       'ddr-rcsv1.zajnb1.prod.ultradns.net',
       'ddr-rcsv2.hkhkg1.prod.ultradns.net', 'u-ci-xtld1.uslax1.ultradns',
       'u-ci-xtld2.uslax1.ultradns', 'u-ci-xtld2.ussea1.ultradns',
       'u-ci-xtld1.usatl1.ultradns', 'u-ci-xtld1.usdal1.ultradns',
       'u-ci-xtld1.usnyc1.ultradns', 'u-ci-xtld2.usdal1.ultradns',
       'u-ci-xtld2.uswas1.ultradns', 'u-ci-xtld1.cator1.ultradns',
       'u-ci-xtld1.uswas1.ultradns', 'u-ci-xtld1.usmia1.ultradns',
       'u-ci-xtld2.uschi1.ultradns', 'u-ci-xtld2.cator1.ultradns',
       'u-ci-xtld1.uschi1.ultradns', 'u-ci-xtld2.jptyo1.ultradns',
       'u-ci-xtld2.usnyc1.ultradns', 'u-ci-xtld2.usatl1.ultradns',
       'u-ci-xtld1.gblon1.ultradns', 'ddr-rcsv2.ussjc1.prod.ultradns.net',
       'ddr-rcsv1.ussjc1.prod.ultradns.net', 'u-ci-xtld1.ausyd1.ultradns',
       'u-ci-xtld2.frpar1.ultradns', 'u-ci-xtld2.gblon1.ultradns',
       'u-ci-xtld2.defra1.ultradns', 'u-ci-xtld1.nlams1.ultradns',
       'u-ci-xtld2.brsao1.ultradns', 'u-ci-xtld2.ausyd1.ultradns',
       'u-ci-xtld1.defra1.ultradns', 'ddr-rcsv2.ussea1.prod.ultradns.net',
       'u-ci-xtld1.brsao1.ultradns', 'u-ci-xtld2.sesto1.ultradns',
       'u-ci-xtld2.nlams1.ultradns', 'ddr-rcsv1.uschi1.prod.ultradns.net',
       'u-ci-xtld1.jptyo1.ultradns', 'u-ci-xtld1.frpar1.ultradns',
       'u-ci-xtld2.sgsin1.ultradns', 'u-ci-xtld1.sesto1.ultradns',
       'u-ci-xtld1.hkhkg1.ultradns', 'ddr-rcsv1.usnyc1.prod.ultradns.net',
       'u-ci-xtld1.sgsin1.ultradns', 'u-ci-xtld2.indel1.ultradns',
       'u-ci-xtld2.inbom1.ultradns', 'u-ci-xtld1.indel1.ultradns',
       'u-ci-xtld2.zajnb1.ultradns', 'ddr-rcsv1.twtpe1.prod.ultradns.net',
       'ddr-rcsv2.twtpe1.prod.ultradns.net',
       'ddr-rcsv2.esmad1.prod.ultradns.net',
       'ddr-rcsv1.hkhkg1.prod.ultradns.net', 'u-ci-xtld1.zajnb1.ultradns',
       'ddr-rcsv1.esmad1.prod.ultradns.net',
       'ddr-rcsv2.inbom1.prod.ultradns.net', 'rcrsv2.ussea1.ultradns',
       'ddr-rcsv2.aedxb1.prod.ultradns.net',
       'ddr-rcsv2.cobog1.prod.ultradns.net',
       'ddr-rcsv1.cobog1.prod.ultradns.net', 'rcrsv3.jptyo1.ultradns',
       'rcrsv2.nlams1.ultradns', 'rcrsv4.nlams1.ultradns',
       'rcrsv2.usnyc1.ultradns', 'rcrsv1.inbom1.ultradns',
       'rcrsv4.brsao1.ultradns', 'rcrsv1.ussjc1.ultradns',
       'rcrsv3.ussjc1.ultradns', 'rcrsv4.ussjc1.ultradns',
       'rcrsv2.ussjc1.ultradns', 'rcrsv3.usnyc1.ultradns',
       'rcrsv1.esmad1.ultradns', 'rcrsv1.twtpe1.ultradns',
       'rcrsv1.hkhkg1.ultradns', 'rcrsv2.esmad1.ultradns',
       'rcrsv2.twtpe1.ultradns', 'rcrsv1.cobog1.ultradns',
       'rcrsv2.frpar1.ultradns', 'rcrsv1.aedxb1.ultradns',
       'rcrsv2.cobog1.ultradns', 'rcrsv2.aedxb1.ultradns',
       'u-ci-xtld2.ussjc1.ultradns', 'u-ci-xtld1.ussjc1.ultradns',
       'u-ci-xtld1.ussea1.ultradns', 'u-ci-xtld2.usmia1.ultradns',
       'u-ci-xtld2.esmad1.ultradns', 'u-ci-xtld2.hkhkg1.ultradns',
       'u-ci-xtld1.esmad1.ultradns', 'u-ci-xtld1.inbom1.ultradns',
       'xtldgd2.usdal201.ultradns', 'xtldgd2.uswas201.ultradns',
       'u-ci-xtld1.aedxb1.ultradns', 'xtldgd1.uswas201.ultradns',
       'xtldgd1.usdal201.ultradns', 'xtldgd1.jptyo201.ultradns',
       'xtldgd2.jptyo201.ultradns', 'xtldgd1.frpar201.ultradns',
       'u-ci-xtld2.twtpe1.ultradns', 'u-ci-xtld1.twtpe1.ultradns',
       'xtldgd2.clscl201.ultradns', 'u-ci-xtld1.cobog1.ultradns',
       'xtldgd2.frpar201.ultradns', 'rcrsv1.frpar1.ultradns',
       'xtldgd1.nlams201.ultradns', 'xtldgd1.ausyd201.ultradns',
       'xtldgd1.brsao201.ultradns', 'xtldgd2.nlams201.ultradns',
       'xtldgd1.aedxb201.ultradns', 'xtldgd2.ausyd201.ultradns',
       'xtldgd1.clscl201.ultradns', 'xtldgd2.sgsin201.ultradns',
       'xtldgd1.sgsin201.ultradns', 'xtldgd2.aedxb201.ultradns',
       'xtldgd2.brsao201.ultradns', 'xtldgd2.zajnb201.ultradns',
       'u-ci-xtld2.cobog1.ultradns', 'u-ci-xtld2.aedxb1.ultradns',
       'xtldgd1.zajnb201.ultradns', 'xtldgd2.ussnn201.ultradns',
       'xtldgd1.ussnn201.ultradns', 'xtldgd2.uschi201.ultradns',
       'xtldgd1.uschi201.ultradns', 'xtldgd1.usmia201.ultradns',
       'xtldgd2.gblon201.ultradns', 'xtldgd2.usmia201.ultradns',
       'xtldgd1.hkhkg201.ultradns', 'xtldgd1.defra201.ultradns',
       'xtldgd2.defra201.ultradns', 'xtldgd2.hkhkg201.ultradns',
       'xtldgd1.gblon201.ultradns', 'xtldgd1.inmaa201.ultradns',
       'xtldgd2.inmaa201.ultradns', 'ddr-rcsv1.aedxb1.prod.ultradns.net',
       'UltraDNS Nameserver', '1762374145.ultradns',
       'UltraDNS TLD b 73d1e494a271e91f4dd7b081fbac2a6b56d12a8b',
       'UltraDNS TLD b c8e364216ad3ca02de97c5248f602303fde5801a'],
      dtype=object)

In [95]:
chaosv4[chaosv4['software'] == 'ultradns']['dst'].nunique()

91

# analysis

In [109]:
# print vps that see dnsmasq the msot often

dnsmasq_data = chaosv4[chaosv4['software'] == 'dnsmasq']

# Count unique destinations per VP
vp_summary = dnsmasq_data.groupby('vp_name').agg(
    unique_dst=('dst', 'nunique')
).reset_index()

# Sort descending to see the VPs that see the most destinations
vp_summary = vp_summary.sort_values(by='unique_dst', ascending=False)

vp_summary

   vp_name  unique_dst
0   blq-it        1555
1  bwi3-us        1555

In [111]:
# exclude blq-it and bwi3-us -> hitting local dnsmasq resolvers

chaosv4 = chaosv4[chaosv4['vp_name'] != 'blq-it']
chaosv4 = chaosv4[chaosv4['vp_name'] != 'bwi3-us']

In [112]:
summary = chaosv4.groupby('software').agg(
    unique_dst=('dst', 'nunique'),
    unique_qname=('qname', 'nunique'),
    unique_record=('record', 'nunique')
).reset_index()

# Aggregate all "known" software (software != 'unknown')
known_row = {
    'software': 'known',
    'unique_dst': chaosv4.loc[chaosv4['software'] != 'unknown', 'dst'].nunique(),
    'unique_qname': chaosv4.loc[chaosv4['software'] != 'unknown', 'qname'].nunique(),
    'unique_record': chaosv4.loc[chaosv4['software'] != 'unknown', 'record'].nunique()
}

# Aggregate total (all software)
total_row = {
    'software': 'total',
    'unique_dst': chaosv4['dst'].nunique(),
    'unique_qname': chaosv4['qname'].nunique(),
    'unique_record': chaosv4['record'].nunique()
}

# Append both rows
summary = pd.concat([summary, pd.DataFrame([known_row, total_row])], ignore_index=True)

summary

   software  unique_dst  unique_qname  unique_record
0      bind         356             5            196
1      core           9             4             33
2      knot          48             4             70
3  powerdns         199             3            249
4    redhat          23             1             20
5  ultradns          91             4            230
6   unknown        2130             6          25018
7     known         682             5            798
8     total        2168             6          25816

In [113]:
unknown = chaosv4[chaosv4['software'] == 'unknown']

unique_dsts_per_record = unknown.groupby('record')['dst'].nunique().reset_index().sort_values(by='dst', ascending=False)
unique_dsts_per_record

                           record  dst
267                             -  321
9924                 Ben Cottrell  314
10223                 Damien Neil  314
10365              Jeremy C. Reed  313
10224                 Danny Mayer  313
...                           ...  ...
13209       cache-toj-leto2350063    1
13210       cache-toj-leto2350065    1
13211       cache-toj-leto2350068    1
13212       cache-toj-leto2350069    1
25017  zuch2.droot.maxgigapop.net    1

[25018 rows x 2 columns]

In [114]:
known = chaosv4[chaosv4['software'] != 'unknown']

In [115]:
# get software per dst

dst_software_counts = known.groupby('dst')['software'].nunique()

dst_multiple_software = dst_software_counts[dst_software_counts > 1].index

dst_multiple_software_rows = known[known['dst'].isin(dst_multiple_software)]

dst_multiple_software_rows[['dst', 'software']].drop_duplicates()

                    dst software
56376       194.0.33.53     knot
59786       194.0.33.53     bind
74517    45.142.220.101     bind
74584    45.142.220.101     knot
119263     194.246.96.1     bind
...                 ...      ...
1372050  195.114.29.130     bind
1372408   109.205.191.4     bind
1373625    91.237.248.2     bind
1376018   5.188.175.100     bind
1386374  15.197.237.120     bind

[86 rows x 2 columns]

In [116]:
# print software found for each

dst_software_list = (
    dst_multiple_software_rows
    .groupby('dst')['software']
    .agg(lambda x: list(x.unique()))
    .reset_index()
)

dst_software_list

               dst              software
0      103.51.60.8        [redhat, bind]
1    109.205.191.4        [redhat, bind]
2   13.248.177.206        [redhat, bind]
3   141.164.24.204        [redhat, bind]
4     15.197.207.2  [core, redhat, bind]
5   15.197.237.120        [redhat, bind]
6    170.247.170.2          [knot, bind]
7    170.247.171.2          [bind, knot]
8    185.131.147.3        [redhat, bind]
9     185.143.80.1          [knot, bind]
10   185.151.141.1          [knot, bind]
11   190.124.27.10          [knot, bind]
12   190.52.162.69        [redhat, bind]
13    192.175.48.1          [knot, bind]
14    192.31.196.1          [knot, bind]
15    193.0.14.129          [knot, bind]
16    193.0.15.254          [knot, bind]
17     193.0.8.254          [knot, bind]
18      193.0.9.83          [knot, bind]
19      194.0.0.53          [bind, knot]
20    194.0.11.104          [knot, bind]
21      194.0.23.5          [knot, bind]
22     194.0.33.53          [knot, bind]
23   194.231.220.1        [redhat, bind]
24    194.246.96.1          [bind, knot]
25  195.114.28.130        [redhat, bind]
26  195.114.29.130        [redhat, bind]
27   199.244.90.99        [bind, redhat]
28   200.16.112.16          [knot, bind]
29       200.7.4.7          [knot, bind]
30    3.33.202.173  [core, redhat, bind]
31    3.33.216.193        [redhat, bind]
32  35.243.187.176        [redhat, bind]
33  45.142.220.101          [bind, knot]
34        45.2.2.2        [redhat, bind]
35   5.188.175.100        [redhat, bind]
36   69.31.181.100        [redhat, bind]
37    76.223.1.101        [redhat, bind]
38   76.223.53.100        [redhat, bind]
39    78.37.72.203        [redhat, bind]
40   91.192.82.100        [redhat, bind]
41    91.237.248.2        [redhat, bind]

In [ ]:
# 103.51.60.8 -> mongolian bank
# 109.205.191.4 -> moldovian telecom?

# 193.0.14.129 -> k-root
# 170.247.171.2 -> b-root

# 192.175.48.1 & 192.31.196.1 (AS112)
# 199.244.90.99 (neustar public recursive resolver)


# AWS global accelorator (route 53)
# 13.248.177.206
# 15.197.207.2
# 15.197.237.120
# 170.247.170.2 & 170.247.171.2
# 3.33.202.173 & 3.33.216.193
# 76.223.1.101 & 76.223.53.100

# google dns endpoint
# 35.243.187.176

# edgecast (verizon) tld auth
# 69.31.181.100

# gcore / swiftycdn
# 5.188.175.100 & 91.192.82.100

# cira (tld auth)
# 45.142.220.101

# apnic rdns
# 103.51.60.8

# ripe admin and rdns
# 109.205.191.4, 193.0.8.254, & 193.0.15.254

# lacnic region ISP
# 190.52.162.69

# frontier networks public resolver
# 45.2.2.2

# russian telecom
# 78.37.72.203

# south korean IX DNS provider
# 141.164.24.204

# clouvider
# 185.131.147.3

# epik nameserver
# 185.143.80.1: